### ISSUE TITLE
Client streamer javascript

### ISSUE THREAD

**Issue by Frenz86** [TiagoPrata/fastapi-frame-stream#1]
Hi Tiago,
this is a very smart solution, thank you so much for your effort. Actually I try to stream a camera by python script,
but is very very slow, in your C# app it works on realtime. Is it possible to find a way to embedded the streamer into
javascript html file, so it will be easier to use it?

Many thanks

#################################################
import cv2
import base64
import json
import requests
import imutils

class BytesEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, bytes):
            return obj.decode('utf-8')
        return json.JSONEncoder.default(self, obj)

url = "http://localhost:8000/send_frame_from_string/stream002" 

cam = cv2.VideoCapture(0)

while (True):
    ret, frame = cam.read()
    frame = imutils.resize(frame, width=320)                     # get frame from webcam
    res, frame = cv2.imencode('.jpg', frame)    # from image to binary buffer
    base64str = base64.b64encode(frame)              # convert to base64 format
    payload = json.dumps({"img_base64str": base64str}, cls=BytesEncoder)
    response = requests.post(url,data = payload)

**Comment by TiagoPrata** [comment]
Hi @Frenz86,

Thanks for your comment.

I've just tested the code you post and it worked pretty normal (see the attached video).

https://user-images.githubusercontent.com/5435108/193822854-30b5a030-4548-4861-a91d-69a6977600ca.mp4

Do you need something faster than that or it is slower in your environment?

**Comment by Frenz86** [comment]
Hi Tiago,
that's make me crazy!!! I tryed on new virtualenv, on linux WSL2, but still got 3-4 FPS.
Please have a look into my repo. Something wrong?
https://github.com/Frenz86/FastAPI_StreamWeb

These's a possibility you got the NASA's hardware?
I have also a quite powerfull laptop, what can cause the problem?

Many thanks
Frenz

**Comment by TiagoPrata** [comment]
Hi @Frenz86,
Right now I'm testing it directly on Windows (instead of WSL2), inside a virtual environment. I don't know it the performance inside WSL2 can be affected.
Apart from that, my laptop is a very common one (i7-7850H, 16Gb RAM, Win10) so I don't think I'm taking any advantage of it.

The video I posted above was testing the same code you shared (which is in the file ```streamer_openc.py``` of your repository), but I also noted that you have another file where you're trying to use streamlit. Actually I've created this library exactly for this purpose. I was trying to send some frames to streamlit and I found no alternative.
I didn't test your streamlit file so far, but the OpenCV one looks fine here.

Later I'll try to have a better look on it, but unfortunately I have no other clue of what is happening for you :(

If you figure something out, please let me know.

**Comment by Frenz86** [comment]
Hi Tiago,
so weird, I also tested on a second laptop (W11 -i7 16GB also the second one), but nothign chnage.
Maybe could be the version of python (I'm using python 3.8). My idea is to use streamlit inside pyodide (stlite) and load the html thanks to jinja template, in order to have the streamer web all in one, with the API server, and make it runner inside a container on google Cloudrun, but latency is killing me :/

Many thanks
Let me know if you find the possible issue.

Frenz

**Comment by Frenz86** [comment]
Hi Tiago,
finally find the solution on stackoverflow, it seems (randomly) put localhost instread 127.0.0.1, it takes 2s every call... Now it works very smooth, I will let you know when I finish this project.

Many thanks
Frenz

**Comment by TiagoPrata** [comment]
Hi @Frenz86,
Fantastic finding. I also didn't know that!

And, yes, please let me know when your project finishes.

BR,
Tiago

**Comment by Frenz86** [comment]
Hi @TiagoPrata , I came across in a couple of good esample. It seems for realtime application, websocket would be easier, and memory optimize for the streaming video. I made some example in this repo, example1 and example2
https://github.com/Frenz86/FastAPI_StreamWebSocket

mi idea is to use fastapi as a machine learning websocket server, and with html, send the camera streaming and receive the object detection etc, for a simple cloud implementation. I am zero to html, do you know how to transform example2 with fastapi ed camera HTML on frontend?

Many thanks
Frenz

**Comment by Frenz86** [comment]
Hi @TiagoPrata , please see my new shared project, finally I solve the problem with Socket
https://github.com/Frenz86/FastSocketAPI

B.R.
Frenz
